### PR TITLE
Refactoring for PYPI and input decoding feature

### PR DESCRIPTION
**Pull request by tintinweb**
This PR adds a feature and refactors the code to ship certain utilities within the package (opviewer for now) still preserving minimal dependencies in case one does not need that feature. This is a preparation to publish `evmlab` on `pypi`.

**refactoring**
* added `evmlab/tools` subpackage
  * tools that we want to make part of the whole package should be placed there. 
  * tools can be made available via cmdline in `__main__.py` as `python -m evmlab <tool_name> <args>`
  * `utilities/...` should then only contain a stub that calls `evmlab.tools.<toolname>.main()`
* setup.py
  * added license
  * made docker, urwid (opviewer), input decoder optional dependencies. need to be installed via `python -m pip install evmlab[abidecoder,consolegui,docker]` as not everyone will need the docker/decoding/ui parts

**features**
* (optionally) transaction input decoding based on the [ethereum-input-decoder](https://github.com/tintinweb/ethereum-input-decoder) project
  * added code to fetch transaction input from remote api
  * this project depends on `eth-abi` which is quite dependecy hungy. The code has bin written in a way that the input decoding is optional. it can be installed via pip `python -m pip install .[abidecoder]`. In case it is not installed it will not decode it and print a warning with installation instructions instead.

image

### CODE REVIEW

**Comment by tintinweb** [comment]
@holiman after merging this PR we should be set to publish `evmlab` to pypi making it available via `pip`.

benefit:
* easy installation
  * `pip install evmlab` (minimal deps)
  * `pip install evmlab[consolegui,abidecoder,docker]` (all extra deps)
* easy cmdline access
  * `python -m evmlab`
  * `python -m evmlab --hash=0x7eda49001bc1fe50df2ed3cc6abb8d6c98c1977d8327b7aced4046c9b8f04628 --web3 https://mainnet.infura.io/remix -v`  (example from screenshot in PR description)

I can publish it for you but I think it makes sense that since its your project you're in control of that package :) This is a quick guide to get it published. you can test everything on testpypi if you do not want to mess things up too much.

1. create an account on pypi --> [pypi/register](https://pypi.org/account/register/)
2. tag master and release it as v0.1 --> [releases](https://github.com/holiman/evmlab/releases)
3. checkout tag v0.1 `git checkout v0.1`
4. do some testing (code)
5. (optional) publish to testpypi for testing
6. publish to productive pypi  (make sure setup.py version is up2date with github release version ;))
6.1 (first time) `python3 setup.py register` and save your pypi profile to `~/.pypirc`
6.2 (for every new release version) `python3 setup.py sdist upload -r pypi`
7. test `python -m pip install evmlab` and `python -m evmlab`

**Comment by holiman** [comment]
Thanks for this. I'm away from home for a while, and want to take a proper look at this when I'm back home. Also, maybe move repo to ethereum org before pypi release. I have not forgotten it, just not had the time to dive into it yet.

**Comment by tintinweb** [comment]
easy, no rush. 👍

**Comment by tintinweb** [comment]
* moved reproducer to tools subpackage and exposed it to `__main__`. it can now be directly called via `python -m evmlab reproducer <args>`
* removed `escape` from reproducer - not needed. 
* refactored zip packing code to be more generic (input files, output archive filename)

**Comment by holiman** [comment]
Sorry it took so long, good work!

**Pull request merged**
