### PR TITLE
refactor phase #1 - opviewer

### PR DESCRIPTION
**Pull request by tintinweb**
Hi,

I've started refactoring `opviewer.py` for reusability. The idea is to have one main entry class for evm-traces `EvmTrace()` that provides all functionality to load traces/memory/data/sources etc and to have another class `DebugViewer()` for visualization. This makes it possible in the future to switch to other trace viewers (especially as `urwid` is not supported on windows).

```python
trace = EvmTrace(api="https://mainnet.infura.io/evmlab")
# 1) from remote api
trace.load_trace(tx="0x......").show()

# 2) from file
trace.load_trace(path="trace.json").show()

# 3) from json object
trace.load_trace(_json=jsondata).show()
```

This PR also adds the following feature:
* fetch tracelog from remote api instead of reproducing it locally: 
`#> python3 opviewer.py --hash 0xbc42444cfa468c1416e4586c2385ea129a56389ef3192ed70826c8aa973a3afb --web3 https://mainnet.infura.io/remix
`  (not really fair to reuse remix api endpoint --> need to talk to infura to get one for evmlab)

:warning: the source-code loading feature has not yet been tested. Would you be able to provide a combined.json (including trace file) for testing purposes and I will make sure to test it and maybe integrate it as a unit-test?

for a list of upcomming changes see `./TODO`.

cheers
tin

### CODE REVIEW

**Comment by holiman** [comment]
Great! 
@perissology , do you have any good test-examples for source code viewer? I haven't used it much myself, I mainly analyze contracts I don't have the source for...

**Comment by holiman** [comment]
@tintinweb Is this still WIP, or do you want this merged now?

**Comment by tintinweb** [comment]
WIP but good to merge @holiman.
I'd suggest to tag the current master and [release it](https://github.com/holiman/evmlab/releases) as v0.1 and then merge this PR.
I am going to create a new PR with more refactoing changes.

**Comment by holiman** [comment]
Thanks!
I've noticed that it's pretty good to create issues for todo-items, that makes it easy for someone who feels like contributing a bit to pick a task and start working.

**Comment by holiman** [comment]
I'll verify the docker image, and experiment a bit, and if it works fine I'll tag a release.

**Comment by tintinweb** [comment]
@holiman - I would suggest to tag the commit before the PR was merged as v0.1 (just to preserve the state before the refactoring) and wait with tagging after merging the PR as there is more to come. 
Will create issues for structured things after the refactoring 👍

**Comment by perissology** [comment]
@tintinweb sorry for taking so long to get some contracts. I've attached a super simple set of contracts to use. I also made #54 to get the source view working again

you can generate a `combined.json` file with the following command:

```solc --combined-json abi,bin-runtime,srcmap,srcmap-runtime,bin PATH_TO_CONTRACTS/* > combined.json```

[contracts.zip](https://github.com/holiman/evmlab/files/2142323/contracts.zip)

**Comment by tintinweb** [comment]
excellent, I'll get my hands on this on friday, thx @perissology

**Pull request merged**
